version: '3.10'

services:
  web:
    build: .
    restart: always
    command: >
      bash -c "python3 manage.py makemigrations
      && python3 manage.py migrate
      && gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
      && python3 manage.py collectstatic --noinput"
    volumes:
      - .:/usr/src/
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db
      - redis
  db:
    image: postgres:11.5-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    env_file: .env
  celery:
    build: .
    command: celery -A portfolio worker -l info --uid=nobody --gid=nogroup
    volumes:
      - .:/usr/src
    env_file: .env
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A portfolio beat -l info
    volumes:
      - .:/usr/src/
    env_file: .env
    depends_on:
      - redis
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      - web

volumes:
  postgres_data:
