# Generated by Django 3.2.12 on 2022-03-22 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("gallery", "0001_initial"),
        ("gallery", "0002_auto_20190912_2031"),
        ("gallery", "0003_auto_20190923_1955"),
        ("gallery", "0004_auto_20191015_1758"),
        ("gallery", "0005_alter_galleryitems_id"),
        ("gallery", "0006_alter_galleryitems_id"),
        ("gallery", "0007_alter_galleryitems_date"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryItems",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos")),
                ("description", models.CharField(max_length=300)),
                ("title", models.CharField(default="Image", max_length=100)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Gallery Items",
            },
        ),
    ]
