# Generated by Django 3.2.12 on 2022-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20191015_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitems',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
