# Generated by Django 3.2.12 on 2022-03-21 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_galleryitems_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitems',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
