# Generated by Django 3.2.12 on 2022-03-22 12:26

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [
        ("pages", "0001_initial"),
        ("pages", "0002_auto_20190830_1931"),
        ("pages", "0003_contactform"),
        ("pages", "0004_auto_20190912_2031"),
        ("pages", "0005_projects_quotes_skills"),
        ("pages", "0006_darkskyapi"),
        ("pages", "0007_auto_20191003_1814"),
        ("pages", "0008_auto_20191015_1758"),
        ("pages", "0009_contactform_viewed"),
        ("pages", "0010_auto_20220305_1535"),
        ("pages", "0011_auto_20220308_1043"),
        ("pages", "0012_auto_20220311_1152"),
        ("pages", "0013_alter_about_options"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("address", models.URLField()),
                ("is_published", models.BooleanField(default=False)),
                ("date", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.CreateModel(
            name="Quotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.CharField(max_length=1000)),
                ("source", models.CharField(max_length=5)),
                ("bg_photo", models.ImageField(upload_to="images/%Y/%m/%d/")),
            ],
            options={
                "verbose_name": "Quote",
                "verbose_name_plural": "Quotes",
            },
        ),
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=100)),
                ("percentage", models.PositiveSmallIntegerField()),
                ("is_published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
            },
        ),
        migrations.CreateModel(
            name="WeatherAPI",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                (
                    "contact_date",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("viewed", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Contact Form",
                "verbose_name_plural": "Contact Forms",
            },
        ),
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", ckeditor.fields.RichTextField()),
            ],
            options={
                "verbose_name": "About Form",
            },
        ),
    ]
