# Generated by Django 2.2.4 on 2019-08-30 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quotes',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
