# Generated by Django 2.2.4 on 2019-09-12 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_contactform"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactform",
            options={
                "verbose_name": "Contact Form",
                "verbose_name_plural": "Contact Forms",
            },
        ),
    ]
