# Generated by Django 2.2.6 on 2019-10-15 17:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_auto_20191003_1814"),
    ]

    operations = [
        migrations.AlterField(
            model_name="darkskyapi",
            name="forecast_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
