# Generated by Django 2.2.6 on 2019-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20191015_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
