# Generated by Django 3.2.12 on 2022-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_contactform_viewed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DarkSkyApi',
        ),
        migrations.AlterField(
            model_name='contactform',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='skills',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
