# Generated by Django 3.2.12 on 2022-03-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20220311_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About Form'},
        ),
    ]
